# The URL the site will be built for
base_url = "https://yousuf.computer"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true
theme = "terminimal"
# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# Optional: enable tags
taxonomies = [{ name = "tags" }]

default_language = "en"

# Code highlighting
[markdown]
highlight_code = true
highlight_theme = "boron"

[extra]
# Put all your custom variables here

# The logo text - defaults to "Terminimal theme"
logo_text = "Yousif Eltayeb"

# The logo link - defaults to base_url.
# logo_home_link = "/take/me/away!"

# Author name: when specified, modifies the default
# copyright text. Apart from author, it will
# contain current year and a link to the theme.
author = "Yousif"


# menu is enabled by adding menu_items (optional)
menu_items = [
    # each of these is optional, name and url are required
    # $BASE_URL is going to be substituted by base_url from configuration

    # tags should only be enabled if you have "tags" taxonomy
    # see documentation below for more details
    { name = "tags", url = "$BASE_URL/tags" },
    { name = "about", url = "$BASE_URL/about" },

    # set newtab to true to make the link open in new tab
    { name = "github", url = "https://github.com/YousifEltayeb", newtab = true },
    { name = "linkedin", url = "https://linkedin.com/in/YousifEltayeb", newtab = true },
]
# The theme supports feeds (RSS and ATOM)
generate_feeds = true

# Use `rss.xml` for RSS feeds and `atom.xml` for ATOM.
feed_filenames = ["rss.xml"]


# Whether to show links to earlier and later posts
# on each post page (defaults to true).
enable_post_view_navigation = true

# The text shown at the bottom of a post,
# before earlier/later post links.
# Defaults to "Thanks for reading! Read other posts?"
post_view_navigation_prompt = "Read more"


# Optional: Global favicon URL and mimetype.
#           Mimetype defaults to "image/x-icon".
#           The URL should point at a file located
#           in your site's "static" directory.
favicon = "/fav.png"
favicon_mimetype = "image/png"


# Optional: Set how <title> elements are rendered.
# Values:
# - "main_only" -- only the main title (`config.title`) is rendered.
# - "page_only" -- only the page title (if defined) is rendered,
#                  falling back to `config.title` if not defined or empty.
# - "combined" -- combine like so: "page_title | main_title",
#                 or if page_title is not defined or empty, fall back to `main_title`
#
# Note that the main (index) page only has the main title.
page_titles = "page_only"
